-- MySQL Script generated by MySQL Workbench
-- 12/03/15 19:00:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema boimcoWeb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boimcoWeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boimcoWeb` DEFAULT CHARACTER SET utf8 ;
USE `boimcoWeb` ;

-- -----------------------------------------------------
-- Table `boimcoWeb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boimcoWeb`.`roles` (
  `idRol` CHAR(3) NOT NULL,
  `descripcionRol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boimcoWeb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boimcoWeb`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idRol` CHAR(3) NOT NULL DEFAULT 'CLT',
  `contraseniaUsuario` VARCHAR(45) NOT NULL,
  `correoUsuario` VARCHAR(45) NOT NULL,
  `fechaIngresoUsuario` DATETIME NOT NULL,
  `intentosUsuario` INT NOT NULL,
  `estadoUsuario` CHAR(3) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `idRol_idx` (`idRol` ASC),
  CONSTRAINT `idRol`
    FOREIGN KEY (`idRol`)
    REFERENCES `boimcoWeb`.`roles` (`idRol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boimcoWeb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boimcoWeb`.`clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `primerNombreCliente` VARCHAR(45) NOT NULL,
  `segundoNombreCliente` VARCHAR(45) NULL,
  `primerApellidoCliente` VARCHAR(45) NOT NULL,
  `segundoApellidoCliente` VARCHAR(45) NULL,
  `direccionCliente` VARCHAR(45) NULL,
  `telefonoCliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `boimcoWeb`.`usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boimcoWeb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boimcoWeb`.`productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `precioUnitarioProducto` FLOAT NOT NULL,
  `cantidadProducto` INT NOT NULL,
  `estadoProducto` CHAR(3) NOT NULL DEFAULT 'ACT',
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boimcoWeb`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boimcoWeb`.`facturas` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `fechaFactura` DATETIME NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `idCliente_idx` (`idCliente` ASC),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `boimcoWeb`.`clientes` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boimcoWeb`.`detalle_facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boimcoWeb`.`detalle_facturas` (
  `idDetalleFactura` INT NOT NULL AUTO_INCREMENT,
  `idFactura` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cantidadProducto` INT NOT NULL,
  `ISV` FLOAT NOT NULL,
  `Total` FLOAT NOT NULL,
  PRIMARY KEY (`idDetalleFactura`),
  INDEX `idFactura_idx` (`idFactura` ASC),
  INDEX `idProducto_idx` (`idProducto` ASC),
  CONSTRAINT `idFactura`
    FOREIGN KEY (`idFactura`)
    REFERENCES `boimcoWeb`.`facturas` (`idFactura`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `boimcoWeb`.`productos` (`idProducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
